### ISSUE TITLE
uint8_t array access returns wrong value

### ISSUE THREAD

**Issue by yanghao** [wlav/cppyy#154]
This is tested under cppyy 3.0.0, but seems to appear since version 2.4.0 already (last working version is 2.3.1).

OS: Ubuntu 22.04
cppyy: 3.0.0
Python: 3.10.6

Reproduce source code:

test.h:
```
#include <stdint.h>

extern uint8_t test[8];
```

test.c:
```
#include <stdint.h>

uint8_t test[8] = {0x12, 0x34, 0x56, 0x78};

```
test.py:
```
from cppyy import gbl as cpp
from cppyy import cppdef, include, load_library, add_include_path

include("test.h")
load_library("test.so")
print([hex(cpp.test[i]) for i in range(8)])
```

Reproduce steps:
```
$ gcc -o test.so -shared test.c
$ python3 test.py
```

Expected prints: 0x12, 0x34, 0x56, 0x78, 0x0, 0x0, 0x0, 0x0
Actual prints (varies for different runs): ['0x7f43335ae020', '0x7f433381b238', '0x1', '0x3', '0x7f432a57cf70', '0x7f432a57cf30', '0x0', '0x5613b4416e10']

Any idea why?

**Comment by yanghao** [comment]
by the way, it seems only "uint8_t" does not work ... all other data type works (16/32/64).

**Comment by yanghao** [comment]
@wlav any idea?

**Comment by wlav** [comment]
Release 3.1.1 has LowLevelViews specialized for `int8_t`/`uint8_t` which solves this.

**Comment by yanghao** [comment]
I can confirm it is fixed, thank you @wlav.

If you care to point out how and where this is fixed I can try to learn a bit of cppyy internals :-)

**Comment by wlav** [comment]
The hard problem is that `int8_t` and `uint8_t` must not be further resolved, otherwise they become `char` and `unsigned char` respectively, so stringy types rather than integers. However, in all other cases, typedefs need to be resolved, in particular to make sure that typedefs and the the types they refer to, map to the same Python instances. If e.g. `int8_t` is used in and of itself, that's simple enough, but if it's part of a chain of typedefs or used in a template name, it's virtually impossible to get right (until there's some support in Cling at some point).

Anyway, I have a few places in cppyy-backend and cppyy-cling where types having `int8_t` and `uint8_t` are filtered out and not further resolved. These are just hacks, nothing earth-shattering. After that, it's simple: create specialized converters for these types (in this case, for custom `LowLevelView` objects).
