### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by NiKeYiGuN** [wlav/cppyy#179]
File "C:\GIT\mymeep\venv\lib\site-packages\cppyy\__init__.py", line 238, in load_library
    sc = gSystem.Load(name)
  File "C:\GIT\mymeep\venv\lib\site-packages\cppyy\__init__.py", line 195, in __exit__
    self.err = _end_capture_stderr()
  File "C:\GIT\mymeep\venv\lib\site-packages\cppyy\_cpython_cppyy.py", line 200, in _end_capture_stderr
    err = _backend._end_capture_stderr()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 187: invalid continuation byte

Possible reasons for this error？

**Comment by wlav** [comment]
That little snippet of code intercepts C++'s `std::cerr`, so that it can raise a Python `RuntimeError` with the contents of what was written to `std::cerr`. The specific use case here is jupyter: `std::cerr` writes to the terminal, not the notebook. This way, the message is retained and made visible, as opposed to lost on a terminal that is likely hidden by some other windows.

What is going on here, is that whatever it captured contains non-ASCII characters. Without knowing the formatting, I'm not sure what to do about it other than perhaps capturing the `UnicodeDecodeError` and showing a more ambiguous message (but still a consistent `RuntimeError`).

Can you call `cppyy.gbl.gSystem.Load()` directly with as argument the same as was given to `cppyy.load_library()`? (The only other thing the latter adds, besides capturing `std::cerr`, is prepending the library name with `lib`, which you may have to do by hand if necessary.) That would then print the error to the terminal, which should give the diagnostic you're looking for.

**Comment by NiKeYiGuN** [comment]
I used cppyy.gbl.gSystem.Load, get the error：LoadLibrary: returned 126: 找不到指定的模块。

**Comment by wlav** [comment]
That "找不到指定的模块" translates as "The specified module could not be found" ... clear enough, no? :) Check the `$PATH` envar to see whether the module can be found that way, or use a full path.

**Comment by NiKeYiGuN** [comment]
C:\GIT\mymeep\venv\Scripts\python.exe C:\GIT\mymeep\pytests\easy_test.py 
cling::DynamicLibraryManager::loadLibrary() [C:\GIT\mymeep\cmake-build-debug\lib
meep\liblibmeep.dll -> C:\GIT\mymeep\cmake-build-debug\libmeep\liblibmeep.dll]:
LoadLibrary: returned 126: 找不到指定的模块。

Process finished with exit code 0

Yes,I use an absolute path,I checked that the dll does exist。

**Comment by wlav** [comment]
Odd as that error message still translates as "The specified module could not be found". Is the module perhaps 32b? Perhaps a better error message can be had from `ctypes`:

```
>>> import ctypes
>>> ctypes.CDLL(r"C:\GIT\mymeep\cmake-build-debug\libmeep\libmeep.dll")
```

(I'm assuming here that the added `lib` is done by `load_library()`, after the one w/o the added `lib` wasn't found. If it is part of the name, obviously add it back.)

**Comment by NiKeYiGuN** [comment]
ctypes.CDLL(r"C:\GIT\mymeep\cmake-build-debug\libmeep\liblibmeep.dll")
  File "C:\Users\guard\AppData\Local\Programs\Python\Python38\lib\ctypes\__init_
_.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\GIT\mymeep\cmake-build-debug\libmee
p\liblibmeep.dll' (or one of its dependencies). Try using the full path with con
structor syntax.

**Comment by NiKeYiGuN** [comment]
import ctypes
    ctypes.CDLL(r"C:\GIT\mymeep\cmake-build-release\libmeep\liblibmeep.dll",winmode=0)

Process finished with exit code 0

**Comment by NiKeYiGuN** [comment]
But how to successfully load_library using cppyy?

**Comment by wlav** [comment]
I can fix it on the cppyy side to add `winmode=0` if failed first and running on Windows and the given path is absolute; it probably doesn't make sense to do this by default.

As a workaround now, you should be able to load the library using:
```
ctypes.CDLL(r"C:\GIT\mymeep\cmake-build-release\libmeep\liblibmeep.dll", ctypes.RTLD_GLOBAL, winmode=0)
```
after which is would be usable by `cppyy` in the same way as when loaded through `gSystem.LoadLibrary()` (there are some subtle differences in symbol resolution that I don't expect to matter, unless e.g. you're redefining symbols from said library through the JIT using `cppyy.cppdef()`).

**Comment by wlav** [comment]
I added the fixes discussed to the repo, but don't have a good way of testing them.

**Comment by NiKeYiGuN** [comment]
OK.

**Comment by wlav** [comment]
Should all be good now with release 3.1.0. Feel free to reopen if you find otherwise.
