### ISSUE TITLE
Failure to install: Python 3.6, Ubuntu 18

### ISSUE THREAD

**Issue by mcowpert** [wlav/cppyy#33]
I was setting up a new system and tried installing the latest cppyy (2.3.0), resulting in multiple “Failed to build” errors and complete failure to install. Version 2.2.0 also failed. Version 2.1.0 did display one or two of those errors (in particular, cppyy_backend) but the installation completed and is working. In each case, the install was attempted into a fresh virtual environment.

Ubuntu 18.04LTS, Python 3.6.9. The environment does not include clang, just gcc 7.5.0.
Installation capture (stdout only) is attached.
[cppyy23_install.log](https://github.com/wlav/cppyy/files/7944366/cppyy23_install.log)

**Comment by wlav** [comment]
Looks like the system has no `cmake` installed. Either install from your distribution or do `python -m pip install cmake`. However, with gcc 7.5.0, the uploaded wheels for `cppyy-cling` should have worked (ie. no build). Furthermore, `cppyy-backend` should not build before `cppyy-cling`.

I'm thinking that you have an ancient version of pip. Likely doing `python -m pip install pip --upgrade` in your virtual environment will solve the issue.

Reasoning:

 1. For old `pip`,  wheel dependencies did not follow source dependencies. Newer `pip` solved did by enforcing the use of a `.toml` file, which `cppyy` now has, while dropping the disabling of wheels (was workaround for old `pip`).
 2. What changed with 2.2.0, is the use of a manylinux2014 wheel only, instead of manylinux1 and -2014 wheels (the former having reached end-of-life). Older `pip` may not know the -2014 tag.

**Comment by mcowpert** [comment]
Thank you! virtualenv sets up the environment with pip 9. Upgrading to current before trying to install cppyy results in a completely clean build process.
