### ISSUE TITLE
method to reload modified c++ code

### ISSUE THREAD

**Issue by xayjin** [wlav/cppyy#54]
hi, cppyy is a wonderful library! I always modify c++ code in repl using cppyy, but cppyy can't reload modified c++ code. I find cppyy get a exist class in the map "gPyClasses" as a cache. 
So I think cppyy need three steps to reload the modified c++ code:
1. erase the class in the map "gPyClasses"
2. delete the class in parent ,such as cppyy.gbl
3. cppexec the code,and use cppyy.gbl to CreateScopeProxy

I fork and add a simple function to act.
[CPyCppyy] src/ProxyWrappers.cxx
```
PyObject* CPyCppyy::DelScopeProxy(PyObject*, PyObject* args)
{
	if (PyTuple_Size(args) < 2){
		std::cout<<"Need two args:nameString parentObject"<<std::endl;
		Py_RETURN_FALSE;
	}
	std::string name = CPyCppyy_PyText_AsString(PyTuple_GetItem(args, 0));
	
	if (PyErr_Occurred())
			Py_RETURN_FALSE;
	Cppyy::TCppScope_t klass = Cppyy::GetScope(name);

	if(!(bool)klass){
		Py_RETURN_FALSE;
	}
	PyClassMap_t::iterator pci = gPyClasses.find(klass);
	if (pci != gPyClasses.end()) {
		gPyClasses.erase(klass);
    		std::string::size_type last = 0;
		PyObject* parent=PyTuple_GetItem(args, 1);

		std::string unscoped = name.substr(last, std::string::npos);
		PyObject_DelAttrString(parent, name.c_str());
	}
	Py_RETURN_TRUE;
}

```
hopely to help.

**Comment by wlav** [comment]
You're right, that _does_ work. But no, `cppexec` doesn't use `ProcessLine()`, which seems to make the difference: `cppdef()` uses `ProcessLine()`, which does _not_ work, and I based my conclusions off that (as well as earlier discussions). I'll still bring it up later with upstream, to see what limitations there are.

Anyway, cool! Let me see how far I can push this. Python's `reload()` may be too much to ask (depending on what happens with shared libraries), but making `__del__` work should be doable.

**Comment by wlav** [comment]
It also doesn't work in namespaces (with `cppexec`).

**Comment by wlav** [comment]
And yes, after discussing with upstream, this is a ROOT feature, not a Cling feature (cppyy still carries ROOT legacy code, enabling this).

The way it works is basically that both methods are kept around in inline namespaces (this is why it doesn't work if the function lives in an actual namespace), with the last definition replacing the previous one in the global symbol lookup table so that subsequent compilation picks the new one. This is indeed quite a flaky approach (it effectively makes Clang's internal state inconsistent) except for specific cases as in the example above, i.e. if use is isolated.

Nevertheless, I'm interested in following the white rabbit and see how far it can be pushed. There are already a few other features that are flaky (e.g. `from cppyy.interactive import *` or `cppyy.ll.signals_as_exception()`) and still useful in confined settings.

**Comment by xayjin** [comment]
Appreciate your reply.Yes, redefinition is not allowed in namespaces except in the global scope.

**Comment by xayjin** [comment]
I find modified function was treated as overloads, not redefinition. That means ```Cppyy::GetMethodIndicesFromName``` from the global scope return all the modified functions. 
So I have a sugguestion: replace ```CPPScope.cxx``` row 371  ```overloads.push_back(```  by ```overloads.insert(overloads.begin(),```. After that, the new modified function will have priority.
By the way, ```delattr(cppyy.gbl,"xxx")``` is needed to relaod from cling backend.

**Comment by xayjin** [comment]
My tricks are not stable. 
Thanks for your wonderful work.

**Comment by wlav** [comment]
Yes and no to the point about overloads. What is going on, is that the compiled stub function is cached in `cppyy-backend` (see https://github.com/wlav/cppyy-backend/blob/master/clingwrapper/src/clingwrapper.cxx#L833). Wipe that, and the same pre-existing overload will recreate a stub, causing a recompilation, new lookup, finding the new call and it will work from there.

So basically `__del__` needs to propagate all the way down to the backend. For cleanliness, it may make sense to delete the intermediate stuff (although finding two overloads isn't a good thing), but it doesn't need to.
