### ISSUE TITLE
cppyy conda package 2.4.0 breaks numba 

### ISSUE THREAD

**Issue by rdemaria** [wlav/cppyy#80]
I am observing this on a fresh installation of miniconda:
```
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
sh ~/Miniconda3-latest-Linux-x86_64.sh -b -p ~/.miniconda3
conda install -y mamba
mamba install -y numba
python -c 'import numba; print(numba.jit(lambda :42)())'
```
I get `42`, but as soon as I 
```
mamba install -y cppyy
python -c 'import numba; print(numba.jit(lambda :42)())'
```
I get 
```
(Re-)building pre-compiled headers (options: -O2 -march=native); this may take a minute ...
Segmentation fault (core dumped)
```

I guess the reason is that conda pulls gcc_linux-64, gxx_linux-64, libllvm9 and somehow numba is not fetching the right libraries anymore, but I am not sure how to solve this

**Comment by rdemaria** [comment]
Using stock `pip install` instead I get:
```
...site-packages/numba/core/dispatcher.py:289: UserWarning: Numba extension module 'cppyy.numba_ext' failed to load due to 'ImportError(.../site-packages/libcppyy.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv)'.
  entrypoints.init_all()
```
but at least numba does not crash...

**Comment by rdemaria** [comment]
Indeed cppyy 2.3.1 is ok on conda.

**Comment by wlav** [comment]
Difference between 2.3.1 and 2.4.0 behavior is clear: the former does not sport `cppyy/numba_ext.py`.

I'm a bit surprised that the numba extension hooks pull in all extension hooks, regardless as to whether the module providing the hooks has already been loaded as well. That seems genuine overkill: `cppyy/numba_ext.py` imports `cppyy` and irrespective of crashing, that's kindof heavy unless you actually use it. I'll see first whether that can be changed, otherwise will more likely disable the extension hooks.

As for crashing in the conda env, not sure (I'm not the dev behind that). Does the installation order matter?

**Comment by rdemaria** [comment]
No it doesn't. It is not clear to what segfaults in numba. gdb showed this:

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffcdb3608d in llvm::TargetPassConfig::addPass(llvm::Pass*, bool, bool) () from .../site-packages/cppyy_backend/lib/../../../../libLLVM-9.so
```
It looks like that when importing cppyy/numba_ext.py, numba picks libLLVM-9.so in the cppyy_backend, rather than libLLVM-10.so

**Comment by wlav** [comment]
cppyy_backend should not link with libLLVM, as that exposes symbols. I guess that's what the conda build does differently from the PyPI package, with the latter failing due to differences in libstdc++ in the conda environment. Anyway, if true, it will not be possible to use cppyy + Numba in a conda environment, only in a pip one.

**Comment by rdemaria** [comment]
Indeed, installing cppyy via pip, solves the problem.

**Comment by saraedum** [comment]
> cppyy_backend should not link with libLLVM, as that exposes symbols.

Could you elaborate on what is happening and what should happen instead?

**Comment by rdemaria** [comment]
Could the conda package be compiled like the PyPi build?

**Comment by saraedum** [comment]
> Could the conda package be compiled like the PyPi build?

We'd rather not link llvm statically. It usually causes a lot of trouble down the line.

So, I don't understand how cppyy and numba can depend on incompatible versions of llvm in conda-forge. If both are linking dynamically, then they're using the same library. And if the dependency setup of llvm is correct in conda-forge, then they should refuse to install with an incompatible llvm version.

**Comment by wlav** [comment]
Patch release 2.4.1 no longer installs the hooks.
